apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-beta
  labels:
    app: app-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-beta
  template:
    metadata:
      labels:
        app: app-beta
    spec:
      containers:
      - name: app-beta
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app-beta-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-beta-html
data:
  index.html: |
    <h1>Hello from App beta</h1>
